# fly.toml app configuration file generated for da-demo on 2023-11-02T11:31:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "da-demo"
primary_region = "waw"

[build]
  image = "vusal946/datingapp:latest"

  [env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dp0uaqcfz"
  CloudinarySettings__ApiKey="312539826629124"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
